version: "3"
services:
  wpscan-docker:
    build: .
    environment:
      - SLACK_OAUTH_TOKEN=${SLACK_OAUTH_TOKEN}
      - WPSCAN_API_TOKEN=${WPSCAN_API_TOKEN}  
      - SLACK_CHANNEL=${SLACK_CHANNEL}  
    restart: always
